#include <gtest/gtest.h>
#include "sysmon/network_monitor.hpp"

TEST(NetworkMonitorTest, ReturnsVector) {
    NetworkMonitor mon;
    // First call initializes internal state (may return empty on first run)
    auto result1 = mon.read();
    auto result2 = mon.read();
    // After two calls, we should have results
    EXPECT_GE(result2.size(), 0u);
}

TEST(NetworkMonitorTest, InterfaceNameNotEmpty) {
    NetworkMonitor mon;
    mon.read(); // warm-up
    auto result = mon.read();
    for (const auto& n : result) {
        EXPECT_FALSE(n.name.empty());
    }
}

TEST(NetworkMonitorTest, RatesNonNegative) {
    NetworkMonitor mon;
    mon.read();
    auto result = mon.read();
    for (const auto& n : result) {
        EXPECT_GE(n.rx_bytes_per_sec, 0.0);
        EXPECT_GE(n.tx_bytes_per_sec, 0.0);
    }
}

// ---------------------------------------------------------------------------
// Routing and resolver parsing
// ---------------------------------------------------------------------------

TEST(NetworkMonitorTest, ParsesDefaultGatewayFromProcNetRoute) {
    // /proc/net/route stores addresses as little-endian hex words.
    // 0101A8C0 == 192.168.1.1
    const std::string content =
        "Iface\tDestination\tGateway \tFlags\tRefCnt\tUse\tMetric\tMask\n"
        "eth0\t0000A8C0\t00000000\t0001\t0\t0\t0\t00FFFFFF\n"
        "eth0\t00000000\t0101A8C0\t0003\t0\t0\t100\t00000000\n";
    EXPECT_EQ(NetworkMonitor::parse_proc_net_route(content), "192.168.1.1");
}

TEST(NetworkMonitorTest, NoDefaultRouteYieldsEmptyGateway) {
    const std::string content =
        "Iface\tDestination\tGateway \tFlags\tRefCnt\tUse\tMetric\tMask\n"
        "eth0\t0000A8C0\t00000000\t0001\t0\t0\t0\t00FFFFFF\n";
    EXPECT_TRUE(NetworkMonitor::parse_proc_net_route(content).empty());
    EXPECT_TRUE(NetworkMonitor::parse_proc_net_route("").empty());
}

TEST(NetworkMonitorTest, ParsesNameserversAndSkipsComments) {
    const std::string content =
        "# generated by resolvconf\n"
        "search example.com\n"
        "nameserver 192.168.1.1\n"
        "nameserver 8.8.8.8 # secondary\n"
        "nameserver 192.168.1.1\n"          // duplicate
        "options edns0\n";
    const auto servers = NetworkMonitor::parse_resolv_conf(content);
    ASSERT_EQ(servers.size(), 2u);
    EXPECT_EQ(servers[0], "192.168.1.1");
    EXPECT_EQ(servers[1], "8.8.8.8");
}

TEST(NetworkMonitorTest, LinkSpeedIsEitherUnsetOrPlausible) {
    NetworkMonitor monitor;
    for (const auto& n : monitor.read()) {
        if (!n.speed_mbps.has_value()) continue;
        // A reported link speed must be a real one, not a zero placeholder.
        EXPECT_GT(n.speed_mbps.value(), 0u) << n.name;
        EXPECT_LE(n.speed_mbps.value(), 1'000'000u) << n.name;
    }
}
